version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    networks:
      - monitoring

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - monitoring
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongodb_exporter:
    image: percona/mongodb_exporter:0.40
    command:
      - '--mongodb.uri=mongodb://mongodb:27017'
    ports:
      - '9216:9216'
    networks:
      - monitoring
    depends_on:
      - mongodb
    environment:
      MONGODB_USER: root
      MONGODB_PASSWORD: example

networks:
  monitoring:
