version: "3"

volumes:
  app_data: {}
  app_data_v2: {}
  grafana-storage: {}
  mongodb_data: {}
  mongodb_logs: {}

networks:
  clase_2_ejemplo_3:

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    volumes:
      - app_data:/app/logs
    networks:
      - clase_2_ejemplo_3

  app_v2:
    build: ./app_v2
    ports:
      - "7000:7000"
    volumes:
      - app_data_v2:/app/logs
    networks:
      - clase_2_ejemplo_3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_logs:/var/log/mongodb
      - ./mongodb/config.conf:/etc/mongo/mongod.conf
    networks:
      - clase_2_ejemplo_3
    command: mongod --config /etc/mongo/mongod.conf

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - clase_2_ejemplo_3
    environment:
      - "GF_DEFAULT_APP_MODE=development"
      - "GF_LOG_LEVEL=debug"
    volumes:
      - ./grafana/grafana.ini.private:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
    ports:
      - 9090:9090
    networks:
      - clase_2_ejemplo_3

  loki:
    image: grafana/loki
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - clase_2_ejemplo_3

  promtail:
    image: grafana/promtail
    volumes:
      - app_data:/var/log/app
      - app_data_v2:/var/log/app_v2
      - mongodb_logs:/var/log/mongodb:ro
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - clase_2_ejemplo_3
