scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - localhost
        labels:
          job: app
          __path__: /var/log/app/*.log
  - job_name: app_v2
    static_configs:
      - targets:
          - localhost
        labels:
          job: app_v2
          __path__: /var/log/app_v2/*.log
  - job_name: mongodb_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: mongodb_logs
          __path__: /var/log/mongodb/mongod.log

clients:
  - url: http://loki:3100/loki/api/v1/push
